# RPI 3B version

udp_helm_listen:
    type:  udp_listen
    outputs:
        - to_helm
    port: 8007

udp_compass_listen:
    type:  udp_listen
    outputs:
        - to_course
    port: 8006

# if defined the input channel configured for type udp_monitor will be used for console reporting and remote logging
udp_monitor:
    type: udp_monitor
    input: to_monitor
    server_address: 192.168.1.166:8005

keys:
    type: keyboard
    outputs: 
      - to_control

control:
    type: controller
    input: to_control

helm:
    type: helm
    p_factor: 100
    i_factor: 100
    d_factor: 100
    gain_factor: 100
    max_helm: 1000
    min_helm: -1000
    centre_helm: 0
    input: to_helm

course:
    type: course
    p_factor: 100
    i_factor: 100
    d_factor: 100
    gain_factor: 100
    input: to_course
