
# Reserved channels:
# command       used for keyboard commands
# so these channels should not be used in inputs or outputs below

udp_send:
    type:  udp_client
    input: to_udp_client
    server_address: 192.168.1.166:8005

udp_compass_listen:
    type:  udp_listen
    outputs:
        - to_udp_client
        - to_course
    port: 8006

udp_helm_listen:
    type:  udp_listen
    outputs:
        - to_udp_client
        - to_helm
    port: 8007

keys:
    type: keyboard
    outputs: 
        - to_udp_client
        - to_helm

helm:
    type: helm
    p_factor: 100
    i_factor: 100
    d_factor: 100
    gain_factor: 100
    input: to_helm

course:
    type: helm
    p_factor: 100
    i_factor: 100
    d_factor: 100
    gain_factor: 100
    input: to_course
